[package]
name = "fake-minecraft-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.57"
lazy_static = "1.4.0"
config = "0.13.3"
num-bigint = "0.4.4"